language: c
compiler: gcc
sudo: required
dist: trusty
env:
  global:
    - MY_PV=1.1.0

before_install:
  - if [ "${COVERITY_SCAN_BRANCH}" = "1" ]; then echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-certificates.crt ; fi

install:
  - sudo add-apt-repository -y ppa:niko2040/e19
  - sudo apt-get -qq update
  - sudo apt-get install -y gettext libc6-dbg libefl libefl-dbg libefl-dev libassuan0 libassuan-dev texinfo
  - wget https://launchpad.net/ubuntu/+source/libgpg-error/1.27-3/+build/12813907/+files/libgpg-error0_1.27-3_amd64.deb
  - wget https://launchpad.net/ubuntu/+source/libgpg-error/1.27-3/+build/12813907/+files/libgpg-error-dev_1.27-3_amd64.deb
  - sudo dpkg -i *.deb

jobs:
  include:
    - stage: Test builds
      env: OPTS="--enable-libsecret --enable-pinentry-curses --enable-pinentry-efl --enable-pinentry-tty --disable-pinentry-fltk --disable-pinentry-gtk2 --disable-pinentry-gnome3 --disable-pinentry-qt"
    - stage: Coverity
      env:
        - secure: x5YM8jcfL9pjgeiyutHUsEOCQ0QL+7mTFb3ppufClYZVfADq2vADSKGtwdPFKy8hP8qX6259oUUA6b7jQXc9UibsaS2LQbHFeT1IrG5h8HqfwVgwItwm14mXcITDz8AT6weK8UwyPgCUJUa1ZG5+LWFhQprJBd6THWQQKTG1P/l1yqd5XjPucnNHxbSv5wZfacADaGY7RnxegEKS/2pRgilcew9EtQezSxQh1Ys+fibu0xNmh+IKROnqekqgquS8PwC3Oink+KxB9hYjZ62Z0Ky13MjLLU7ECHjd5T0W45cDy2MKeJbNGkK+GDChphIVjZwuYnJ3s0huaQSz9OCzNy9TilSRG86l+1QeBcJdjutqxhTjibSpkNv47frZFNh/D2TtyVtovBzegHph4zeSEzByXWoeCFiUbZ0p4iW29xobDRTYc05jGuAEyW3n1E0KaWEb4S0+vkr3XRbybPM1UU7sZP+igoJ24v53aEixSddjTTsOIU+CpIkOAc7iIs0G5hpqCcWCaRXEkyuQWv/WIHl77u3r03bKxhEbIsb+kt4WdlvcNWkhsaJpZWG22DWNbiQoWgZd2E7OCm2Oo0lDObwdjBRdYN+yGw3yQe82ZOSpImPIxucBUWBhjPxZsafThyDJ78yqgY2/eLxqx4HCIzpO7sp+MOK4RBsHzu/b+Og=
        - OPTS="--enable-libsecret --enable-pinentry-curses --enable-pinentry-efl --enable-pinentry-tty --disable-pinentry-fltk --disable-pinentry-gtk2 --disable-pinentry-gnome3 --disable-pinentry-qt"
      addons:
        coverity_scan:
          project:
            name: Obsidian-StudiosInc/pinentry
            description: Build submitted via Travis CI
          notification_email: wlt@o-sinc.com
          build_command_prepend: "autoreconf -f -i && automake && ./configure ${OPTS}; make clean"
          build_command: make -j4
          branch_pattern: master

script:
  - echo "@set UPDATED "`date +"%d %B %Y"`"" > doc/version.texi
  - echo "@set UPDATED-MONTH "`date +"%d %B"`"" >> doc/version.texi
  - echo "@set EDITION ${MY_PV}" >> doc/version.texi
  - echo "@set VERSION ${MY_PV}" >> doc/version.texi
  - ./autogen.sh
  - ./configure ${OPTS} && make

notifications:
  email: false
