language: c
compiler: gcc
sudo: required
dist: trusty
env:
  global:
    - MY_PV=1.1.0

cache:
  directories:
    - $HOME/.sonar/cache

install:
  - sudo add-apt-repository -y ppa:niko2040/e19
  - sudo apt-get -qq update
  - sudo apt-get install -y gettext libc6-dbg libefl libefl-dbg libefl-dev libassuan0 libassuan-dev texinfo
  - wget https://launchpad.net/ubuntu/+source/libgpg-error/1.27-3/+build/12813907/+files/libgpg-error0_1.27-3_amd64.deb
  - wget https://launchpad.net/ubuntu/+source/libgpg-error/1.27-3/+build/12813907/+files/libgpg-error-dev_1.27-3_amd64.deb
  - sudo dpkg -i *.deb

jobs:
  include:
    - stage: Test builds
      env: OPTS="--enable-libsecret --enable-pinentry-curses --enable-pinentry-efl --enable-pinentry-tty --disable-pinentry-fltk --disable-pinentry-gtk2 --disable-pinentry-gnome3 --disable-pinentry-qt"
    - stage: Sonar Cloud
      env:
        - OPTS="--enable-libsecret --enable-pinentry-curses --enable-pinentry-efl --enable-pinentry-tty --disable-pinentry-fltk --disable-pinentry-gtk2 --disable-pinentry-gnome3 --disable-pinentry-qt"
        - SONAR="0"
      addons:
        sonarcloud:
          organization: obsidian-studiosinc-github
          token:
            secure: SrsitQEglRTCLcEQ7mIsSR9zL4qdNM8OzBdvN/2yWn//YM437R4beZGZEGw7OAifa9/VzEVddqXmAz3B6HRSyawy1PEKA2i/xF0/pHw/UMoEtGiKK34XES4VDt6DcOzY6k2CXBTEO/rWo+XtF2GBpvWtTc47UmBF1J70TEkbORZkuKbIYjDmLz0tK//3b/FPWFtHyHHWMfJVyvQ38Hr2u22HyUueaFAdk3ZlUT/10sxuka47fn8wMVB5Kv6Dfnb0DNSW3yO4U0A84Td3+Mt8B7AmVEvQ3AczWIDK+UTiWul5j91PLOnh7aJRq/aRlZsFCNOJH8X/U62YGqCVtfmpEl3/3z/asibExsL8KXQ9Y6BfqXTaJfHAU17Az9o6g2hJcnyitTkvLZe0RMIW+bKdi/pyL79Ji778x9RNfEjVzBzSSf8UrpY9WP5PG8zNkT6Vy0+KwSc03PRv7obiB59mdO8iJJ8yVDyerF93juo3INiFUu5WQoge5HTncP6PPJCHpCklbrqQioODzh/1TwvfpjUgzNZcPBwXcRznXYicLVgE+Ph7Jb6TyBg0Vw6sESWpD8X64NLl3H03ZAsJfzZYT5l99VpNH7L9e28v2IogVaOKSCOCgH1vdALS/2V8GfAtBOh4pHXcQ0FaEd9iM7gXupduGzOt3FS+epXPSgvdhSs=

script:
  - echo "@set UPDATED "`date +"%d %B %Y"`"" > doc/version.texi
  - echo "@set UPDATED-MONTH "`date +"%d %B"`"" >> doc/version.texi
  - echo "@set EDITION ${MY_PV}" >> doc/version.texi
  - echo "@set VERSION ${MY_PV}" >> doc/version.texi
  - ./autogen.sh
  - ./configure ${OPTS}
  - if [ "${SONAR}" = "0" ]; then build-wrapper-linux-x86-64 --out-dir bw-output make; fi
  - if [ "${SONAR}" = "0" ]; then sonar-scanner; else make; fi

notifications:
  email: false
